
all: dependency2 dependency1
	@echo "This main projects depends on dependency1 and dependency2 to build"

dependency1:
	@echo "This is a dependency 1"

dependency2:
	@echo "This is a dependency 2"


